"""
ToC Critique Data Models
Pydantic schemas for "intelligent failure" prompts
Date: 2026-06-25
"""

from pydantic import BaseModel, Field
from typing import List, Optional
from uuid import UUID
from datetime import datetime


class TocCritique(BaseModel):
    """
    An "intelligent failure" critique of a ToC.
    
    These are adversarial prompts generated by a separate GPT critique pass
    that surface historical failures in similar contexts. Users must acknowledge
    these before locking a ToC (PRD US-01).
    """
    id: Optional[UUID] = None
    toc_id: UUID = Field(..., description="ToC being critiqued")
    prompt: str = Field(
        ...,
        min_length=20,
        description="The failure prompt (e.g., 'Similar youth-jobs pilots failed when...')"
    )
    source_ids: List[UUID] = Field(
        default_factory=list,
        description="Evidence sources backing this critique"
    )
    acknowledged: bool = Field(
        default=False,
        description="Whether user has acknowledged this critique"
    )
    severity: Optional[str] = Field(
        None,
        description="Severity level (high, medium, low)"
    )
    category: Optional[str] = Field(
        None,
        description="Failure category (e.g., 'assumption_breach', 'context_mismatch')"
    )
    created_at: Optional[datetime] = None


class CritiqueGenerationRequest(BaseModel):
    """Request to generate critiques for a ToC."""
    toc_id: UUID = Field(..., description="ToC to critique")
    graph: dict = Field(..., description="ToC graph structure")
    context: dict = Field(
        default_factory=dict,
        description="Context (region, population, etc.)"
    )


class CritiqueGenerationResponse(BaseModel):
    """Response from critique generation."""
    critiques: List[TocCritique] = Field(..., description="Generated critiques")
    tokens_used: int = Field(..., description="Tokens consumed by the critique pass")
    generation_time_ms: int = Field(..., description="Generation time")


class CritiqueAcknowledgment(BaseModel):
    """User acknowledgment of a critique."""
    critique_id: UUID = Field(..., description="Critique being acknowledged")
    user_id: UUID = Field(..., description="User acknowledging")
    notes: Optional[str] = Field(
        None,
        description="Optional notes on how this will be addressed"
    )
    acknowledged_at: datetime = Field(default_factory=datetime.utcnow)


class CritiqueSummary(BaseModel):
    """Summary of critiques for a ToC."""
    toc_id: UUID
    total_critiques: int = Field(..., description="Total number of critiques")
    acknowledged_count: int = Field(..., description="Number acknowledged")
    unacknowledged_count: int = Field(..., description="Number not yet acknowledged")
    can_lock: bool = Field(
        ...,
        description="Whether ToC can be locked (all critiques acknowledged)"
    )
    critiques: List[TocCritique] = Field(..., description="All critiques")

# Made with Bob
